inherit: true
filter:
    paths: [src/*]
    excluded_paths: [tests/*]
tools:
    php_code_coverage: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'